### ISSUE TITLE
unable to open preferences on Gnome 40.5 / Ubuntu / Debian based Distros

### ISSUE THREAD

**Issue by crysman** [deinstapel/cpupower#186]
I've posted it already here
https://github.com/deinstapel/cpupower/issues/158#issuecomment-1080003994
Thanks for help!

**Comment by fin-ger** [comment]
Executable bit is not set for `/usr/share/gnome-shell/extensions/cpupower@mko-sl.de/src/prefs40/main.js`. To (temporarily) fix this run:

```
$ sudo chmod +x /usr/share/gnome-shell/extensions/cpupower@mko-sl.de/src/prefs40/main.js
```

**Comment by crysman** [comment]
resolved here https://github.com/deinstapel/cpupower/issues/158#issuecomment-1086133002

**Comment by fin-ger** [comment]
No no no :D

Not resolved. This is quite a serious issue. Needs to stay open until someone (my time is currently very limited) fixes the issue.

**Comment by fin-ger** [comment]
"Fixing" means updating the apt package.

**Comment by crysman** [comment]
> No no no :D
> 
> Not resolved. This is quite a serious issue. Needs to stay open until someone (my time is currently very limited) fixes the issue.

Agree, sorry to be impetuous, glad you re-opened and glad I've found a potential serious bug ;)

**Comment by Pear-sudo** [comment]
> 

I have the same problem on Gnome 42.2, Ubuntu 22.04.1 LTS ([following the official installation guide](https://github.com/deinstapel/cpupower#any-newer-ubuntu-release-or-ubuntu-based-distribution-if-unsure-do-this)). And this command works. Thank you!
